spring.application.name=CepteFinansBackend

# --- PostgreSQL Ayarlar? ---
spring.datasource.url=jdbc:postgresql://localhost:5433/ceptefinans_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# --- Redis Ayarlar? ---
spring.data.redis.host=localhost
spring.data.redis.port=6379

# --- Logging Ayarlar? (Winston/Zap alternatifi) ---
# Spring Boot varsay?lan olarak Logback kullan?r, çok güçlüdür.
logging.level.root=INFO
logging.level.com.arvenlabs.ceptefinansbackend=DEBUG
logging.file.name=logs/ceptefinansbackend.log

# ... di?er ayarlar?n ...
spring.jpa.open-in-view=false