spring.application.name=CepteFinansBackend

# --- PostgreSQL Ayarlari ---
spring.datasource.url=jdbc:postgresql://localhost:5433/ceptefinans_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# --- Redis Ayarlari ---
spring.data.redis.host=localhost
spring.data.redis.port=6379

# --- Logging Ayarlari (Winston/Zap alternatifi) ---
# Spring Boot varsayilan olarak Logback kullanir, çok güçlüdür.
logging.level.root=INFO
logging.level.com.arvenlabs.ceptefinansbackend=DEBUG
logging.file.name=logs/ceptefinansbackend.log

# ... diger ayarlarin ...
spring.jpa.open-in-view=false
