spring.application.name=CepteFinansBackend

# --- PostgreSQL Ayarlar? ---
spring.datasource.url=jdbc:postgresql://localhost:5433/ceptefinans_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# --- Redis Ayarlar? ---
spring.data.redis.host=localhost
spring.data.redis.port=6379

# --- Logging Ayarlar? (Winston/Zap alternatifi) ---
# Spring Boot varsay?lan olarak Logback kullan?r, çok güçlüdür.
logging.level.root=INFO
logging.level.com.arvenlabs.ceptefinansbackend=DEBUG
logging.file.name=logs/ceptefinansbackend.log

# ... di?er ayarlar?n ...
spring.jpa.open-in-view=false

# --- Spring Mail (Zoho SMTP) Ayarlari ---
spring.mail.host=smtp.zoho.eu
spring.mail.port=587
spring.mail.username=hesapli@arvenlabs.com
spring.mail.password=AEkkNa94dkMZ
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- Spring Mail (Zoho SMTP) Ayarlari ---
spring.mail.host=smtp.zoho.eu
spring.mail.port=587
spring.mail.username=hesapli@arvenlabs.com
spring.mail.password=AEkkNa94dkMZ
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

zoho.account.id=1000.6E4J07DWTQ52WIP7GNQ1EE0H7Z0QLA
zoho.api.access-token=ba2d4968f4c04e0cf96aa5d89cf80de23141e4304b

app.frontend.url=http://localhost:3000
